/**
 * DOM reports rendered as vault notes.
 *
 * Pure: builds filenames and file contents. Writing them is the sync apply
 * step's job, behind the confirm gate.
 */

/** Where exported reports live, relative to the vault root. */
export const REPORT_DIR = ['06-Gnosis', 'DOM-Reports']

/** Local wall clock, matching how DOM itself dates a report. */
const pad = (n) => String(n).padStart(2, '0')

/**
 * `DOM-2026-07-30-2015.md`.
 *
 * Local time, not UTC. FlowJournal used `toISOString()`, so a report written
 * in the CET evening exported under the following day's filename while its own
 * header said today.
 *
 * @param {string|number|Date} createdAt
 */
export function reportFilename(createdAt) {
  const d = new Date(createdAt)
  return `DOM-${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}-${pad(d.getHours())}${pad(d.getMinutes())}.md`
}

/**
 * The note body. Frontmatter is fixed: these files are generated by us, so the
 * tier is asserted rather than classified, and `tier_by` records who vouched
 * for it.
 */
export function reportNote({ created_at: createdAt, scope, report }) {
  const d = new Date(createdAt)
  const date = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`

  return [
    '---',
    'tier: 1',
    'tier_by: abbe',
    'source: "DOM report"',
    'topic: dom-report',
    '---',
    '',
    `# DOM Report — ${date}`,
    '',
    `Scope: ${scope ?? ''}`,
    '',
    report ?? '',
    '',
  ].join('\n')
}

/**
 * Which reports have no file yet.
 *
 * @param {Array<object>} reports rows from dom_reports
 * @param {Set<string>} existingFilenames already in the vault
 */
export function reportsToExport(reports, existingFilenames) {
  return reports
    .map((row) => ({ row, filename: reportFilename(row.created_at) }))
    .filter(({ filename }) => !existingFilenames.has(filename))
}
